name: Create new Release (Frontend)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/release.yml'

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v4

      - uses: TriPSs/conventional-changelog-action@v5
        with:
          version-file: './package.json'
          pre-commit: './.build/inject-library-version.js'
          github-token: ${{ secrets.github_token }}

      - name: Update version in src/version.ts
        run: |
          sed -i "s/version: '.*'/version: '${{ steps.changelog.outputs.version }}'/" src/version.ts

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
